let num = 10;
const greet = "Hello TypeScript";
const isOn = true;
const person = { name: "손흥민", age: 10 };
const numbers = [1, 2, 3, 4, 5, 6];
const bts = ["진", "슈가", "제이홉"];
const item = ["손흥민", 30, true];
let name = "손흥민";
name = 1;
// num = "hello";
let empty = null;
let notAssigned = undefined;
export {};
